### ISSUE TITLE
Cannot build an enclave file after a couple of successful runs of nitro-cli build-enclave

### ISSUE THREAD

**Issue by charlolizard** [aws/aws-nitro-enclaves-cli#282]
After a couple of successful builds nitro-cli crashes with:
`Linuxkit reported an error while creating the customer ramfs: "Add init containers: 
Process init image: docker.io/library/<my image>
Add files: 
rootfs/dev
rootfs/run
rootfs/sys
rootfs/var
rootfs/proc
rootfs/tmp
cmd
env
Create outputs:"`

The /log/nitro-enclaves says:
`Action: Build Enclave
  Subactions:
    Failed to build enclave
    Failed to build EIF from docker
    Failed to create EIF image: LinuxkitExecError
  Root error file: src/lib.rs
  Root error line: 152
  Build commit: v1.0.10-42-gde77067
`
The only solution to fix this that I have found is to restart EC2 machine.

**Comment by alcioa** [comment]
@charlolizard is this issue still happening? What size is your docker image and the instance size?

**Comment by charlolizard** [comment]
Sorry for the late reply, it has cleared itself.

**Comment by charlolizard** [comment]
It looks like this issue appears again, now I am not able to fix it with restart. I am trying to convert this application: https://hub.docker.com/r/fortanix/python-flask

**Comment by charlolizard** [comment]
This is happening on a images close to and bigger than 1 GB in size.

**Comment by russellhaering** [comment]
I just resolved this for myself. There are multiple potential causes, but one that I think might be hitting people here:

There is an upper limit of 1GB on image sizes, caused by how `nitro-cli` is invoking linuxkit (see: https://github.com/linuxkit/linuxkit/issues/3759).

One possibility is that your docker image is just naturally over 1GB.

But what happened to me is that I was building `.eif` images and dumping them out into the same directory where I'm building docker images. Then the next time I built a docker image it would copy in the previous `.eif` file, making each image recursively larger than the last.

The quickest fix for early experimenting is just to add `*.eif` to a `.dockerignore` file in the root of your repository.

**Comment by davidnugent2425** [comment]
This issue seems to be due to a lack of available RAM on the instance which is running the build. I was getting this error message until I increased the amount of RAM I had available on my instance. Now I am able to build images much larger than 1GiB, which shows that it's not a linuxkit issue.
The larger the image you are trying to build, the more RAM you will need.

**Comment by imentus-rahul** [comment]
I'm facing similar issue. 
My docker image size is 4.58GB

When I try to build the nitro-enclave with above image, I get following error: Linuxkit reported an error while creating the customer ramfs: "Add init containers:\nProcess init image: docker.io/library/mpc-server:latest\nAdd files:\n  rootfs/dev\n  rootfs/run\n  rootfs/sys\n  rootfs/var\n  rootfs/proc\n  rootfs/tmp\n  cmd\n  env\nCreate outputs:\n"

I'm using c6.2xlarge (16GB, 70GB), I've changed default /etc/nitro_enclaves/allocator.yaml with memory as 10240, and restarted allocator service. Still facing same issue. 

Is it even possible or not, to have docker size more than 1 GB in nitro-enclave image file?

**Comment by twneale** [comment]
I had a similar issue. After watching memory closely, the EIF build for a 6GB image was blowing up and consuming all 15G of memory on my box. I booted a much larger VM with 64GB memory and the EIF file built easily in 10 seconds. I haven't succeeded in running it yet, but anyone who finds this thread: you need a bigger boat. That is all.
