### ISSUE TITLE
vsock and Mysql

### ISSUE THREAD

**Issue by bert2002** [aws/aws-nitro-enclaves-cli#411]
Hi,
has anyone ever tried to use vsock with Mysql/MariaDB? I have an application that I want to run in the Nitro Enclave, but it needs a Mysql database to connect to. Since the vsock is limited I wonder if this will work.

Thanks,
bert

**Comment by alcioa** [comment]
Hi, not that I am aware of since this is user-side application design.

If your DB server endpoint listens on TCP/UDP connections you could try working on a solution for forwarding the networking traffic over the vsock channel and proxy it on the EC2 instance side to your endpoint. 

Hope this answers your question. Will close due to off-topic to this project.
